services:

  postgres:
    container_name: sops-postgres
    image: postgres:latest
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sops_db

  redis:
    container_name: sops-redis
    image: redis:latest
    ports:
      - "6379:6379"
    entrypoint:

volumes:
  postgres_db: